---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

f_1 = list(
  family = "sans serif",
  size = 10,
  color = 'light gray')

f_2 = list(
  family = "sans serif",
  size = 10,
  color = 'light gray')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
 ny_noaa %>%
  mutate(
    prcp = round(prcp/254, digits = 2)
  ) %>%
  filter(
    date > "2010-10-01",
    prcp > 0
  ) %>%
  drop_na() %>%
  plot_ly(
    x = ~id,
    y = ~prcp,
    color = ~id,
    colors = "viridis",
    type = "scatter",
    mode = "markers") %>%
  layout(title = "Scatter Plot of Precipitation (in) vs. Weather Station ID", font = f_1,
         xaxis = list(title = "Weather Station ID", f_2),
         yaxis = list(title = "Precipitation (in)", f_2))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>%
  mutate(
    snow = round(snow/25.4, digits = 3)
  ) %>%
  filter(
    snow > 1,
    date > "2009-09-01", 
    date < "2010-09-01"
  ) %>%
  drop_na() %>%
  mutate(
    id = fct_reorder(id, snow)
  ) %>%
  plot_ly(
    y = ~snow,
    x = ~id,
    color = ~id,
    type = "box",
    colors = "viridis"
  ) %>%
  layout(title = "Box Plot of Recorded Snowfall (in) by Weather Station ID", font = f_1,
         xaxis = list(title = "Weather Station ID", font = f_2),
         yaxis = list(title = "Snowfall (in)", font = f_2))
```

### Chart C

```{r}
ny_noaa %>%
  count(id) %>%
  mutate(
  id =fct_reorder(id, n)
  ) %>%
  plot_ly(x = ~id, y = ~n, type = "bar", color = ~id, colors = "viridis") %>%
  layout(title = "Bar Plot of Number of Observations by Weather Station ID", font = f_1,
         xaxis = list(title = "Weather Station ID", font = f_2),
         yaxis = list(title = "Number of Observations", font = f_2))
```

